services:
  - type: web
    name: linkguard-backend
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: CLERK_API_KEY
        sync: false
      - key: CLERK_JWT_PUBLIC_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
