services:
  - type: web
    name: linkguard-backend
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: PYTHONPATH
        value: "."
      - key: PYTHON_VERSION
        value: "3.11.2"
      - key: DATABASE_URL
        sync: false
      - key: CLERK_API_KEY
        sync: false
      - key: CLERK_JWT_PUBLIC_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLERK_WEBHOOK_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
